### ISSUE TITLE
[Question] How to update binaries inside a jail?

### ISSUE THREAD

**Issue by TLINDEN** [BastilleBSD/bastille#772]
**[MANDATORY] Describe the bug [MANDATORY]**
I am about to build an ansible deployment to deploy FreeBSD vm's and - among other things - to deploy bastille based jails.

One of the jails contains a go binary. I am deploying the jail as usual:
```
bastille create ...
bastille start ...
bastille template ...
```
Said go binary is part of the template.

In the case with the go binary, this only works once. When I execute the deployment a 2nd time (which would be the case if there's a newer version of the go binary), I get:

```
cp: /usr/local/bastille/jails/chat/root/usr/local/sbin/devzat: Text file busy
Failed to execute command: cp
```

The reason is, that the binary is actually running. But if I stop it, `bastille template` doesn't run. I don't know how to solve this.

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
```
0.10.20231125
14.2-RELEASE
```

**[MANDATORY] How did you install bastille? (port/pkg/git)**
pkg

**[optional] Steps to reproduce?**
These are the ansible tasks I am running in this order

```yaml
- name: copy devzat binary
  shell: install -m 755 /tmp/devzat/devzat /usr/local/bastille/templates/services/{{ role_name }}/usr/local/sbin/devzat

- name: create jail
  shell: "bastille create -B {{ role_name }} {{ release }} {{ chatip.stdout }}/64 bridge0"
  args:
    creates: /usr/local/bastille/jails/{{ role_name }}

- name: start jail
  shell: bastille start {{ role_name }} || true

- name: template jail
  shell: "bastille template {{ role_name }} services/{{ role_name }}"
```

**[optional] Expected behavior**
I'd need a way to update binaries inside a jail. Ideally a non-running jail, but not using manual copy commands. So, stopping the jail, copying the file and starting it would do the job, but then I'd not use bastille anymore.
